// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ti2_Andre_API.Models;

namespace Ti2_Andre_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190706162538_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Ti2_Andre_API.Models.Comentarios", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EpisodioFK");

                    b.Property<string>("Texto");

                    b.HasKey("ID");

                    b.HasIndex("EpisodioFK");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Ti2_Andre_API.Models.Editora", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Logo");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Editoras");
                });

            modelBuilder.Entity("Ti2_Andre_API.Models.Episodios", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Classificacao");

                    b.Property<string>("Foto");

                    b.Property<string>("Nome");

                    b.Property<int>("Numero");

                    b.Property<string>("Sinopse");

                    b.Property<int>("TemporadaFK");

                    b.Property<string>("Trailer");

                    b.HasKey("ID");

                    b.HasIndex("TemporadaFK");

                    b.ToTable("Episodios");
                });

            modelBuilder.Entity("Ti2_Andre_API.Models.Pessoas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Foto");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Ti2_Andre_API.Models.PessoasEpisodios", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EpisodioFK");

                    b.Property<int>("Papel");

                    b.Property<int>("PessoaFK");

                    b.HasKey("ID");

                    b.HasIndex("EpisodioFK");

                    b.HasIndex("PessoaFK");

                    b.ToTable("PessoasEpisodios");
                });

            modelBuilder.Entity("Ti2_Andre_API.Models.Series", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuxClassificacao");

                    b.Property<double>("Classificacao");

                    b.Property<int>("EditoraFK");

                    b.Property<string>("Foto");

                    b.Property<string>("Genero");

                    b.Property<string>("Nome");

                    b.Property<string>("Sinopse");

                    b.Property<string>("Video");

                    b.HasKey("ID");

                    b.HasIndex("EditoraFK");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Ti2_Andre_API.Models.Temporadas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Foto");

                    b.Property<string>("Nome");

                    b.Property<int>("Numero");

                    b.Property<int>("SerieFK");

                    b.Property<string>("Trailer");

                    b.HasKey("ID");

                    b.HasIndex("SerieFK");

                    b.ToTable("Temporadas");
                });

            modelBuilder.Entity("Ti2_Andre_API.Models.Comentarios", b =>
                {
                    b.HasOne("Ti2_Andre_API.Models.Episodios", "Episodios")
                        .WithMany("ListaDeComentarios")
                        .HasForeignKey("EpisodioFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ti2_Andre_API.Models.Episodios", b =>
                {
                    b.HasOne("Ti2_Andre_API.Models.Temporadas", "Temporadas")
                        .WithMany("Episodios")
                        .HasForeignKey("TemporadaFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ti2_Andre_API.Models.PessoasEpisodios", b =>
                {
                    b.HasOne("Ti2_Andre_API.Models.Episodios", "Episodios")
                        .WithMany("PessoasEpisodios")
                        .HasForeignKey("EpisodioFK")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ti2_Andre_API.Models.Pessoas", "Pessoas")
                        .WithMany("PessoasEpisodios")
                        .HasForeignKey("PessoaFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ti2_Andre_API.Models.Series", b =>
                {
                    b.HasOne("Ti2_Andre_API.Models.Editora", "Editora")
                        .WithMany("Series")
                        .HasForeignKey("EditoraFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ti2_Andre_API.Models.Temporadas", b =>
                {
                    b.HasOne("Ti2_Andre_API.Models.Series", "Series")
                        .WithMany("Temporadas")
                        .HasForeignKey("SerieFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
